#!/usr/bin/env node
/* Generates SEO artifacts from data/catalog.js (the single source of truth):
   - injects a crawlable <noscript> catalog into index.html (between the SEO markers)
   - writes sitemap.xml
   Deterministic (no timestamps) so CI can check the artifacts stay in sync.
   Run: `npm run build:seo`. */
import { readFileSync, writeFileSync } from 'node:fs';
import vm from 'node:vm';

const root = new URL('../', import.meta.url);
const SITE = 'https://maneesh-kumar-thakur.github.io/self-serve-learnings-4-all/';
const START = '<!-- SEO:START (generated by scripts/build-seo.mjs - do not edit) -->';
const END = '<!-- SEO:END -->';

const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(readFileSync(new URL('data/catalog.js', root), 'utf8'), sandbox);
const cat = sandbox.window.CATALOG;

const esc = (s) => String(s == null ? '' : s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

const topics = (cat.topics && cat.topics.length) ? cat.topics : [{ id: 'llms', name: cat.topic || 'Catalog' }];
const topicOf = (t) => t.topic || 'llms';
let body = '';
body += `<h2>${cat.tools.length} AI/ML tools by concept depth (Level 0 to 4)</h2>\n`;
body += `<p>A searchable, leveled learning map of ${cat.tools.length} AI and machine-learning tools across ${topics.length} topics. Every tool links to an approachable article to read and to its code or homepage. Enable JavaScript for search, autocomplete and level/category filters.</p>\n`;
for (const tp of topics) {
  const tTools = cat.tools.filter((t) => topicOf(t) === tp.id);
  if (!tTools.length) continue;
  body += `<h2>${esc(tp.name)}</h2>\n`;
  for (const lv of cat.levels.slice().sort((a, b) => a.n - b.n)) {
    const tools = tTools.filter((t) => t.level === lv.n);
    if (!tools.length) continue;
    body += `<h3>Level ${lv.n} — ${esc(lv.name)}</h3>\n<p>${esc(lv.blurb || '')}</p>\n`;
    for (const c of [...new Set(tools.map((t) => t.category))]) {
      body += `<h4>${esc(c)}</h4>\n<ul>\n`;
      for (const t of tools.filter((x) => x.category === c)) {
        const read = t.read && t.read.url ? ` — <a href="${esc(t.read.url)}">Read${t.read.title ? ': ' + esc(t.read.title) : ''}</a>` : '';
        const code = t.code && t.code.url ? ` · <a href="${esc(t.code.url)}">${t.code.kind === 'homepage' ? 'Website' : 'Code'}</a>` : '';
        body += `<li><strong>${esc(t.name)}</strong>${t.note ? ' (' + esc(t.note) + ')' : ''}${read}${code}</li>\n`;
      }
      body += `</ul>\n`;
    }
  }
}

// Inject into index.html between the markers
const indexPath = new URL('index.html', root);
let html = readFileSync(indexPath, 'utf8');
const re = new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
if (!re.test(html)) { console.error('ERROR: SEO markers not found in index.html'); process.exit(1); }
html = html.replace(re, `${START}\n<noscript>\n${body}</noscript>\n${END}`);
writeFileSync(indexPath, html);

// sitemap.xml — deterministic lastmod from catalog.updated
const lastmod = /^\d{4}-\d{2}-\d{2}$/.test(cat.updated || '') ? cat.updated : '2026-07-22';
writeFileSync(new URL('sitemap.xml', root),
`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${SITE}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`);

console.log(`build:seo OK — injected ${cat.tools.length} tools into index.html <noscript> and wrote sitemap.xml (lastmod ${lastmod}).`);
